export const ACT_OBTER_PROJETOS = 'ACT_OBTER_PROJETOS'
export const ACT_CADASTRAR_PROJETOS = 'ACT_CADASTRAR_PROJETOS'
export const ACT_ALTERAR_PROJETOS = 'ACT_ALTERAR_PROJETOS'
export const ACT_DELETAR_PROJETOS = 'ACT_DELETAR_PROJETOS'

export const ACT_OBTER_TAREFAS = 'ACT_OBTER_TAREFAS'
export const ACT_CADASTRAR_TAREFA = 'ACT_CADASTRAR_TAREFA'
export const ACT_ALTERAR_TAREFA = 'ACT_ALTERAR_TAREFA'